### ISSUE TITLE
Very very very tiny amounts of enhance points in H8?

### ISSUE THREAD

**Issue by rreed** [Jacorb90/Prestige-Tree#1]
Hello! I'm not actually sure if this is a bug, but I certainly can't figure out why it would happen mechanically, and I have no idea how else to progress if it's NOT a bug, so I'm filing this issue. :)

Basically, whenever I start H8, by the time the timer stops, I have either 3e-10 or 6e-20 enhance points. I have no idea how to get a fraction of an enhance point, but the challenge seems basically impossible and really random. If I start the challenge and do nothing, it dies at about ~e4100 points. If I start the challenge and IMMEDIATELY hit E, it instead dies at about e13.5-e14k points, which doesn't really seem intended at all, considering that everything on layer 3 is auto and "no reset" by this point.

I've also noticed that this challenge seems to stop ticking up at around two seconds rather than the ten the description claims.

Am I just missing something extremely obvious? I'm at 33/36 Space and 11/12 Boosters and this seems like what the game wants me to do to push myself over the wall.

Here's a pastebin of my savefile, if that helps: https://pastebin.com/8G1htVMq

Thanks for the game, it's a neat idea!

**Comment by Jacorb90** [comment]
This is intended. H8 is a strategy-based challenge. Instead of hitting E instantly, hit it after about a second (or when you are at 1e1,000 points-ish).

**Comment by Arcorann** [comment]
I got stuck here too. The challenge disabling autogeneration of Enhance Points really should be added to the description of the challenge, it looks like this is a common problem.

**Comment by Jacorb90** [comment]
I mean it doesn't disable generation, but because it slows down time, it slows down that auto-generation.

**Comment by Arcorann** [comment]
I didn't think that the slowdown would be so dramatic as to stop auto-generation almost completely, but I looked at the code and did the calculation, and it turns out it is that dramatic. I was quite surprised by that.

**Comment by Jacorb90** [comment]
Yeah it is quite dramatic, and intentionally so. I'm gonna close this now because it's not really a bug, and now there is a hint at the challenge for anyone who didn't know to press 'E'.
