### ISSUE TITLE
H10 seemingly impossible when playing on Firefox.

### ISSUE THREAD

**Issue by Kyromyr** [Jacorb90/Prestige-Tree#2]
After over a hundred attempts the best result I got was e326k points. At first I thought I was just underpowered for it and had to wait for 69 space, but then I got the idea to play on Chrome. First try, e476k points.

**Comment by Jacorb90** [comment]
Hmm... that is quite odd, could you send me your save? My discord server is https://discord.gg/wwQfgPa, so you can DM me there if you aren't already in the server.

**Comment by Kyromyr** [comment]
Save's in the pastebin. Also including a short video showcasing it.

https://pastebin.com/gNCu7QiT
https://dl.dropboxusercontent.com/s/lfqw7hy7q68bpbq/vlc-record-2020-09-05-17h41m04s-Replay_2020.09.05-17.40.mp4-.mp4

**Comment by Jacorb90** [comment]
Okay well I took that save and tried it in Firefox and instantly completed it (e450k points-ish)... so idk why it isn't working for you. My suggestion would be to make sure you don't have any offline time (that may make you lose enhancers faster than you should? idk)

**Comment by Jacorb90** [comment]
Closed since it's fixed with the rewrite
