### ISSUE TITLE
Exponent not in scientific notation for exponents less than -1,000,000,000

### ISSUE THREAD

**Issue by James103** [Jacorb90/Prestige-Tree#3]
When you run the "Anti-Enhancers" hinderance for long enough, something like the following can occur, where the exponent (itself a very large negative number) is not correctly formatted in scientific notation, it stays in comma-separated notation even as it passes -1,000,000,000 and beyond. It's only when the exponent reaches -9,000,000,000,000,000 that it changes the notation to double-logarithmic. Note that the precision is still respected, as it still is only showing up to 4 significant figures (3 decimal places in scientific notation).
![image](https://user-images.githubusercontent.com/37945304/92792565-41443880-f373-11ea-95f6-9ec51f50be4a.png)

**Comment by Jacorb90** [comment]
Oh I believe that's an oversight by me when creating the function to format numbers, I'll fix that soon, thanks for letting me know.

**Comment by Jacorb90** [comment]
This has been fixed I believe, so i will close this now
