### ISSUE TITLE
Stuck longer than expected in "Upgrade Desert"

### ISSUE THREAD

**Issue by GSUI5051** [Jacorb90/Prestige-Tree#9]
After I do a Row 5 prestige, Hindrance challenge is reset. When I enter Upgrade Desert, game stucks for a while, longer than expected

**Comment by GSUI5051** [comment]
Save: 
[Bug Save.txt](https://github.com/Jacorb90/Prestige-Tree/files/5923623/Bug.Save.txt)

**Comment by Jacorb90** [comment]
Not a bug. I tried with your save and everything was perfectly fine on my end. 
Make sure to remember to purchase Prestige & Booster upgrades in the challenge!

I'd recommend checking out the prestige tree discord if you need any further help (link in-game on the discord logo).
